# Generated by Django 4.2.11 on 2024-04-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("berita", "0002_alter_artikel_options_alter_kategori_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artikel",
            old_name="katagori",
            new_name="kategori",
        ),
    ]
