# Generated by Django 4.2.11 on 2024-03-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pengguna", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="biodata",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="pengguna"),
        ),
    ]
